site_name: Compose Window Styler
site_description: A library that lets you style your Compose for Desktop window to have more native and modern UI.
site_author: MayakaApps
site_url: https://mayakaapps.github.io/ComposeWindowStyler
repo_name: ComposeWindowStyler
repo_url: https://github.com/MayakaApps/ComposeWindowStyler
copyright: Copyright &copy; 2022-2025 MayakaApps. # Also, update copyright notice in Dokka
remote_branch: gh-pages

nav:
  - 'Overview': index.md
  - 'API Reference': api/index.html

theme:
  name: 'material'
  favicon: images/logo.png
  logo: images/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: 'indigo'
      accent: 'pink'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: 'indigo'
      accent: 'pink'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.action.view

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.critic
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - macros
  - mike

extra:
  versions:
    library: !ENV [LIBRARY_VERSION]
  version:
    provider: mike
